<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Login Email Address</name>
   <tag></tag>
   <elementGuidId>1da672ac-1356-4d04-a7f6-83613f420ae0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='_com_liferay_login_web_portlet_LoginPortlet_login']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#_com_liferay_login_web_portlet_LoginPortlet_login</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Email Address&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2e1e213d-d686-4671-8546-84a08f394223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field clearable form-control</value>
      <webElementGuid>5947e316-8591-4bbd-8b06-412d682f8c72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_com_liferay_login_web_portlet_LoginPortlet_login</value>
      <webElementGuid>359b0c04-aa66-4885-8a21-4c4757210c83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_com_liferay_login_web_portlet_LoginPortlet_login</value>
      <webElementGuid>2213dc5f-1aef-4659-a2d6-5ded74598861</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3f1f5c39-be81-4730-a282-bea2dd1b212f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>44592400-f7c6-4eac-b01f-3de38865a574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_com_liferay_login_web_portlet_LoginPortlet_login&quot;)</value>
      <webElementGuid>52e8b265-9a2a-4b42-b6b2-dd590b448d6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_com_liferay_login_web_portlet_LoginPortlet_login']</value>
      <webElementGuid>1462e820-8144-4bda-a9dc-a2f08af1d5c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='_com_liferay_login_web_portlet_LoginPortlet_loginForm']/fieldset/fieldset/div/div/input</value>
      <webElementGuid>ce56826a-72d8-4bc4-b12b-fb4f91a2bb78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>e39d8cf8-552e-483b-8dea-ee35d61b6711</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '_com_liferay_login_web_portlet_LoginPortlet_login' and @name = '_com_liferay_login_web_portlet_LoginPortlet_login' and @type = 'text']</value>
      <webElementGuid>d5331691-5ae3-4d8f-8f93-16c7c0dd816d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
