<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Login Password</name>
   <tag></tag>
   <elementGuidId>54d71126-8e1c-45a7-8225-d709e1d89b72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='_com_liferay_login_web_portlet_LoginPortlet_password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#_com_liferay_login_web_portlet_LoginPortlet_password</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Password&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5ff1c051-65d3-4c8e-ab58-56271d41064e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field form-control</value>
      <webElementGuid>fbaa684b-c06d-45ff-a3da-f308a65aab5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_com_liferay_login_web_portlet_LoginPortlet_password</value>
      <webElementGuid>141ca588-3373-4b17-b836-0021461acaa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_com_liferay_login_web_portlet_LoginPortlet_password</value>
      <webElementGuid>cb7c56b7-aad5-4f18-8571-3a136b409626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>94874bac-163b-47eb-93be-a57bffb69db6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>48b8229e-28dc-496a-8ea9-ba79f13ed369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_com_liferay_login_web_portlet_LoginPortlet_password&quot;)</value>
      <webElementGuid>dab90b03-aaf5-4147-8157-c91b0026ddee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_com_liferay_login_web_portlet_LoginPortlet_password']</value>
      <webElementGuid>2964d0d6-1bfe-4664-a421-a4451ef71aaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='_com_liferay_login_web_portlet_LoginPortlet_loginForm']/fieldset/fieldset/div/div[2]/input</value>
      <webElementGuid>cea274b6-a90c-4c26-ba3e-931b37da2d75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>5aff7730-5a58-4305-bb39-ccc43110b31e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '_com_liferay_login_web_portlet_LoginPortlet_password' and @name = '_com_liferay_login_web_portlet_LoginPortlet_password' and @type = 'password']</value>
      <webElementGuid>e9d7f991-5739-4f38-b7a0-5c8998f8f2da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
